### ISSUE TITLE
Study and practice array functions

### ISSUE THREAD

**Issue by brunos3d** [gabrieldejesus/practice-javascript#1]
It is very important that every javascript developer knows how to use array functions with mastery

### Challenge
Learn functions like `push`, `pop`, `splice`, `map`, `filter`, `reduce`...

### Resources
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array

https://jstutorial.medium.com/map-filter-and-reduce-animated-7fe391a35a47

https://www.geeksforgeeks.org/javascript-basic-array-methods/

https://www.codingame.com/playgrounds/6181/javascript-arrays---tips-tricks-and-examples

**Comment by gabrieldejesus** [comment]
Thank you very much for the suggestion @BrunoS3D 🚀
