### ISSUE TITLE
Learning about requests with XMLHR, Promises and Fetch API

### ISSUE THREAD

**Issue by caiodomingues** [gabrieldejesus/practice-javascript#4]
XMLHttpRequests, Promises and the Fetch API are fundamental not only for working with data, but it also helps understanding many parts and functionalities of JavaScript.

### XMLHttpRequest

- https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest
- https://www.w3schools.com/xml/xml_http.asp

### Promises

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
- https://www.w3schools.com/js/js_promise.asp

### Fetch API

- https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
- https://www.w3schools.com/js/js_api_fetch.asp

**Comment by gabrieldejesus** [comment]
Thank you very much for your suggestion
You got me excited @caiodomingues
